services:
  db:
    image: postgres:15-alpine
    container_name: pitang-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker_pass
      - POSTGRES_DB=pitang_project
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
